Repository Requisitos-de-Software/2021.2-PontoFacil, pull requests merged in 2022-04, with the labels that each got.

#62 #61 - Elaboração da EAP
  docs/assets/imagens/eap.png
  docs/pos_rastreabilidade/eap.md
  mkdocs.yml
Labels: Documentação, Pós Rastreabilidade

#60 #59 - Backward_from Pull request
  docs/pos_rastreabilidade/backward_from.md
Labels: Documentação, Pós Rastreabilidade

#63 Pós rastreabilidade forward from
  docs/pos_rastreabilidade/forward_from.md
  mkdocs.yml
Labels: Documentação, Pós Rastreabilidade

#70 #69 Documento de Disponibilidade
  docs/planejamento/cronograma.md
  docs/planejamento/disponibilidade.md
Labels: Documentação, correções

#77 Correção no documento de ferramentas
  docs/assets/logos/figma.png
  docs/assets/logos/githubpng.png
  docs/assets/logos/logo-canva.png
  docs/assets/logos/logo-discord.png
  docs/assets/logos/logo-figma.png
  docs/assets/logos/logo-generator.png
  docs/assets/logos/logo-github.png
  docs/assets/logos/logo-jamboard.png
  docs/assets/logos/logo-lucid.png
  docs/assets/logos/logo-mkdocs.png
  docs/assets/logos/logo-sheets.png
  docs/assets/logos/logo-teams.png
  docs/assets/logos/logo-vscode.png
  docs/assets/logos/logo-whatsapp.jpg
  docs/assets/logos/logo-youtube.png
  docs/assets/logos/wpppng.png
  docs/assets/logos/youtube.png
  docs/planejamento/ferramentas.md
Labels: Documentação, correções

#79 #71 - Tabela de divisão por pessoa
  docs/planejamento/cronograma.md
Labels: correções

#78 Correção no documento de casos de uso
  docs/assets/imagens/Casos de uso -geral.svg
  docs/assets/imagens/Casos de uso-apagar-registros-passados.svg
  docs/assets/imagens/Casos de uso-ativar-notificacoes.svg
  docs/assets/imagens/Casos de uso-fazer-backup.svg
  docs/assets/imagens/Casos de uso-gerar-extrato.svg
  docs/assets/imagens/Casos de uso-inconsistencias.svg
  docs/assets/imagens/Casos de uso-registrar-falta.svg
  docs/assets/imagens/Casos de uso-registrar-ponto.svg
  docs/assets/imagens/diagrama_use_case_PontoFacil.svg
  docs/modelagem/casos_de_uso.md
Labels: Documentação, correções

#81 Correção dos documentos de verificação em geral
  docs/analise/verificacao/planejamento_verificacao.md
  docs/analise/verificacao/ver_casos_de_uso.md
  docs/analise/verificacao/ver_cenarios.md
  docs/analise/verificacao/ver_moscow.md
  docs/analise/verificacao/ver_nfr_framework.md
  docs/analise/verificacao/ver_personas.md
  docs/assets/imagens/possiveis_erros_casos_de_uso.PNG
  docs/assets/imagens/template_verificacao.PNG
  docs/assets/imagens/template_verificacao_tab.PNG
  docs/assets/imagens/template_verificacao_tab_vazia.PNG
  docs/assets/imagens/ver_caso_de_uso_01.PNG
  docs/assets/imagens/ver_caso_de_uso_01_checklist.PNG
  docs/assets/imagens/ver_caso_de_uso_02.PNG
  docs/assets/imagens/ver_caso_de_uso_02_checklist.PNG
  docs/assets/imagens/ver_caso_de_uso_03.PNG
  docs/assets/imagens/ver_caso_de_uso_03_checklist.PNG
  docs/assets/imagens/ver_caso_de_uso_04.PNG
  docs/assets/imagens/ver_caso_de_uso_04_checklist.PNG
  docs/assets/imagens/ver_caso_de_uso_05.PNG
  docs/assets/imagens/ver_caso_de_uso_05_checklist.PNG
  docs/assets/imagens/ver_caso_de_uso_06.PNG
  docs/assets/imagens/ver_caso_de_uso_06_checklist.PNG
  docs/assets/imagens/ver_caso_de_uso_07.PNG
  docs/assets/imagens/ver_caso_de_uso_07_checklist.PNG
  docs/assets/imagens/ver_cenario01_resultado.PNG
  docs/assets/imagens/ver_cenario02_resultado.PNG
  docs/assets/imagens/ver_cenario03_resultado.PNG
  docs/assets/imagens/ver_cenario04_resultado.PNG
  docs/assets/imagens/ver_cenario05_resultado.PNG
  docs/assets/imagens/ver_cenario06_resultado.PNG
  docs/assets/imagens/ver_cenario_01_grafico.PNG
  docs/assets/imagens/ver_cenario_02_grafico.PNG
  docs/assets/imagens/ver_cenario_03_grafico.PNG
  docs/assets/imagens/ver_cenario_04_grafico.PNG
  docs/assets/imagens/ver_cenario_05_grafico.PNG
  docs/assets/imagens/ver_cenario_06_grafico.PNG
  docs/assets/imagens/ver_personas_grafico.PNG
  docs/assets/imagens/ver_personas_resultado.PNG
  mkdocs.yml
Labels: Documentação, correções

#82 Correção nas referencias em geral e correções gerais
  docs/analise/verificacao/ver_casos_de_uso.md
  docs/analise/verificacao/ver_cenarios.md
  docs/analise/verificacao/ver_personas.md
  docs/elicitacao/priorizacao/moscow.md
  docs/elicitacao/tecnicas/questionario.md
  docs/modelagem/especificacao_suplementar.md
  docs/modelagem/lexicos.md
  docs/planejamento/ferramentas.md
  docs/planejamento/metodologia.md
  docs/pos_rastreabilidade/backward_from.md
  docs/pre_rastreabilidade/rich_pictures.md
Labels: Documentação, correções

#85 Correções lorenzo
  docs/modelagem/backlog/userstories/us01.md
  docs/modelagem/backlog/userstories/us02.md
  docs/modelagem/backlog/userstories/us03.md
  docs/modelagem/backlog/userstories/us04.md
  docs/modelagem/backlog/userstories/us05.md
  docs/modelagem/backlog/userstories/us06.md
  docs/modelagem/backlog/userstories/us07.md
  docs/modelagem/backlog/userstories/us08.md
  docs/modelagem/backlog/userstories/us09.md
  docs/modelagem/backlog/userstories/us10.md
  docs/modelagem/backlog/userstories/us11.md
  docs/modelagem/backlog/userstories/us12.md
  docs/modelagem/backlog/userstories/us13.md
  docs/modelagem/backlog/userstories/us14.md
  docs/modelagem/backlog/userstories/us15.md
  docs/modelagem/backlog/userstories/us16.md
  docs/modelagem/backlog/userstories/us17.md
  docs/modelagem/backlog/userstories/us18.md
  docs/modelagem/backlog/userstories/us19.md
  docs/modelagem/backlog/userstories/us20.md
  docs/modelagem/backlog/userstories/us21.md
  docs/modelagem/backlog/userstories/us22.md
  docs/modelagem/backlog/userstories/us23.md
  docs/modelagem/backlog/userstories/us24.md
  docs/modelagem/backlog/userstories/us25.md
  docs/modelagem/backlog/userstories/us26.md
  docs/modelagem/backlog/userstories/us27.md
  docs/modelagem/backlog/userstories/us28.md
  docs/modelagem/backlog/userstories/us29.md
  docs/modelagem/backlog/userstories/us30.md
  docs/modelagem/backlog/userstories/us31.md
  docs/modelagem/backlog/userstories/us32.md
  docs/modelagem/backlog/userstories/us33.md
  docs/modelagem/backlog/userstories/us34.md
  docs/modelagem/backlog/userstories/us35.md
  docs/planejamento/metodologia.md
  docs/planejamento/politica_rep.md
  mkdocs.yml
Labels: Documentação, enhancement, Modelagem
